<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'ProxyManager\\' => array($vendorDir . '/ocramius/proxy-manager/src'),
    'Neos\\Neos\\Ui\\Compiled' => array($baseDir . '/Packages/Application/Neos.Neos.Ui.Compiled/Classes'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'Flowpack\\Neos\\FrontendLogin' => array($baseDir . '/Packages/Plugins/Flowpack.Neos.FrontendLogin/Classes'),
    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Behat\\Transliterator' => array($vendorDir . '/behat/transliterator/src'),
);
