<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf5d5e17d8bcc6e5757c5f3af607b4a7d
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'Z' => 
        array (
            'Zend\\EventManager\\' => 18,
            'Zend\\Code\\' => 10,
        ),
        'T' => 
        array (
            'TYPO3Fluid\\Fluid\\' => 17,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Polyfill\\Ctype\\' => 23,
            'Symfony\\Component\\Yaml\\' => 23,
            'Symfony\\Component\\DomCrawler\\' => 29,
            'Symfony\\Component\\Console\\' => 26,
        ),
        'R' => 
        array (
            'Ramsey\\Uuid\\' => 12,
        ),
        'P' => 
        array (
            'Psr\\SimpleCache\\' => 16,
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Container\\' => 14,
            'Psr\\Cache\\' => 10,
            'PackageVersions\\' => 16,
        ),
        'N' => 
        array (
            'Neos\\Utility\\Unicode\\' => 21,
            'Neos\\Utility\\Lock\\' => 18,
            'Neos\\Utility\\' => 13,
            'Neos\\Twitter\\Bootstrap\\' => 23,
            'Neos\\SiteKickstarter\\' => 21,
            'Neos\\Setup\\' => 11,
            'Neos\\Seo\\' => 9,
            'Neos\\RedirectHandler\\NeosAdapter\\' => 33,
            'Neos\\RedirectHandler\\DatabaseStorage\\' => 37,
            'Neos\\RedirectHandler\\' => 21,
            'Neos\\Party\\' => 11,
            'Neos\\NodeTypes\\Navigation\\' => 26,
            'Neos\\NodeTypes\\Html\\' => 20,
            'Neos\\NodeTypes\\Form\\' => 20,
            'Neos\\NodeTypes\\ContentReferences\\' => 33,
            'Neos\\NodeTypes\\ColumnLayouts\\' => 29,
            'Neos\\NodeTypes\\BaseMixins\\' => 26,
            'Neos\\NodeTypes\\AssetList\\' => 25,
            'Neos\\NodeTypes\\' => 15,
            'Neos\\Neos\\Ui\\' => 13,
            'Neos\\Neos\\' => 10,
            'Neos\\Media\\Browser\\' => 19,
            'Neos\\Media\\' => 11,
            'Neos\\Kickstarter\\' => 17,
            'Neos\\Imagine\\' => 13,
            'Neos\\Fusion\\' => 12,
            'Neos\\Form\\' => 10,
            'Neos\\FluidAdaptor\\' => 18,
            'Neos\\Flow\\Log\\' => 14,
            'Neos\\Flow\\Core\\Migrations\\' => 26,
            'Neos\\Flow\\' => 10,
            'Neos\\Error\\Messages\\' => 20,
            'Neos\\Eel\\' => 9,
            'Neos\\Diff\\' => 10,
            'Neos\\Demo\\' => 10,
            'Neos\\ContentRepository\\' => 23,
            'Neos\\ComposerPlugin\\' => 20,
            'Neos\\Cache\\' => 11,
        ),
        'G' => 
        array (
            'Gedmo\\' => 6,
        ),
        'D' => 
        array (
            'Doctrine\\ORM\\' => 13,
            'Doctrine\\Instantiator\\' => 22,
            'Doctrine\\DBAL\\Migrations\\' => 25,
            'Doctrine\\Common\\Inflector\\' => 26,
            'Doctrine\\Common\\Cache\\' => 22,
            'Doctrine\\Common\\Annotations\\' => 28,
            'Doctrine\\Common\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Zend\\EventManager\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-eventmanager/src',
        ),
        'Zend\\Code\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-code/src',
        ),
        'TYPO3Fluid\\Fluid\\' => 
        array (
            0 => __DIR__ . '/..' . '/typo3fluid/fluid/src',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'Symfony\\Component\\Yaml\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/yaml',
        ),
        'Symfony\\Component\\DomCrawler\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/dom-crawler',
        ),
        'Symfony\\Component\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/console',
        ),
        'Ramsey\\Uuid\\' => 
        array (
            0 => __DIR__ . '/..' . '/ramsey/uuid/src',
        ),
        'Psr\\SimpleCache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'PackageVersions\\' => 
        array (
            0 => __DIR__ . '/..' . '/ocramius/package-versions/src/PackageVersions',
        ),
        'Neos\\Utility\\Unicode\\' => 
        array (
            0 => __DIR__ . '/..' . '/neos/utility-unicode/Classes',
        ),
        'Neos\\Utility\\Lock\\' => 
        array (
            0 => __DIR__ . '/..' . '/neos/utility-lock/Classes',
        ),
        'Neos\\Utility\\' => 
        array (
            0 => __DIR__ . '/..' . '/neos/utility-arrays/Classes',
            1 => __DIR__ . '/..' . '/neos/utility-files/Classes',
            2 => __DIR__ . '/..' . '/neos/utility-mediatypes/Classes',
            3 => __DIR__ . '/..' . '/neos/utility-objecthandling/Classes',
            4 => __DIR__ . '/..' . '/neos/utility-opcodecache/Classes',
            5 => __DIR__ . '/..' . '/neos/utility-pdo/Classes',
            6 => __DIR__ . '/..' . '/neos/utility-schema/Classes',
        ),
        'Neos\\Twitter\\Bootstrap\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Twitter.Bootstrap/Classes',
        ),
        'Neos\\SiteKickstarter\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.SiteKickstarter/Classes',
        ),
        'Neos\\Setup\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Setup/Classes',
        ),
        'Neos\\Seo\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Seo/Classes',
        ),
        'Neos\\RedirectHandler\\NeosAdapter\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.RedirectHandler.NeosAdapter/Classes',
        ),
        'Neos\\RedirectHandler\\DatabaseStorage\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.RedirectHandler.DatabaseStorage/Classes',
        ),
        'Neos\\RedirectHandler\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.RedirectHandler/Classes',
        ),
        'Neos\\Party\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Party/Classes',
        ),
        'Neos\\NodeTypes\\Navigation\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.NodeTypes.Navigation/Classes',
        ),
        'Neos\\NodeTypes\\Html\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.NodeTypes.Html/Classes',
        ),
        'Neos\\NodeTypes\\Form\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.NodeTypes.Form/Classes',
        ),
        'Neos\\NodeTypes\\ContentReferences\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.NodeTypes.ContentReferences/Classes',
        ),
        'Neos\\NodeTypes\\ColumnLayouts\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.NodeTypes.ColumnLayouts/Classes',
        ),
        'Neos\\NodeTypes\\BaseMixins\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.NodeTypes.BaseMixins/Classes',
        ),
        'Neos\\NodeTypes\\AssetList\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.NodeTypes.AssetList/Classes',
        ),
        'Neos\\NodeTypes\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.NodeTypes/Classes',
        ),
        'Neos\\Neos\\Ui\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Neos.Ui/Classes',
        ),
        'Neos\\Neos\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Neos/Classes',
        ),
        'Neos\\Media\\Browser\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Media.Browser/Classes',
        ),
        'Neos\\Media\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Media/Classes',
        ),
        'Neos\\Kickstarter\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Framework/Neos.Kickstarter/Classes',
        ),
        'Neos\\Imagine\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Imagine/Classes',
        ),
        'Neos\\Fusion\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Fusion/Classes',
        ),
        'Neos\\Form\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Form/Classes',
        ),
        'Neos\\FluidAdaptor\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Framework/Neos.FluidAdaptor/Classes',
        ),
        'Neos\\Flow\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/neos/flow-log/Classes',
        ),
        'Neos\\Flow\\Core\\Migrations\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Framework/Neos.Flow/Scripts/Migrations',
        ),
        'Neos\\Flow\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Framework/Neos.Flow/Classes',
        ),
        'Neos\\Error\\Messages\\' => 
        array (
            0 => __DIR__ . '/..' . '/neos/error-messages/Classes',
        ),
        'Neos\\Eel\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Framework/Neos.Eel/Classes',
        ),
        'Neos\\Diff\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Diff/Classes',
        ),
        'Neos\\Demo\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Sites/Neos.Demo/Classes',
        ),
        'Neos\\ContentRepository\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.ContentRepository/Classes',
        ),
        'Neos\\ComposerPlugin\\' => 
        array (
            0 => __DIR__ . '/..' . '/neos/composer-plugin/Classes',
        ),
        'Neos\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/neos/cache/Classes',
        ),
        'Gedmo\\' => 
        array (
            0 => __DIR__ . '/..' . '/gedmo/doctrine-extensions/lib/Gedmo',
        ),
        'Doctrine\\ORM\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/orm/lib/Doctrine/ORM',
        ),
        'Doctrine\\Instantiator\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/instantiator/src/Doctrine/Instantiator',
        ),
        'Doctrine\\DBAL\\Migrations\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/migrations/lib/Doctrine/DBAL/Migrations',
        ),
        'Doctrine\\Common\\Inflector\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/inflector/lib/Doctrine/Common/Inflector',
        ),
        'Doctrine\\Common\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/cache/lib/Doctrine/Common/Cache',
        ),
        'Doctrine\\Common\\Annotations\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/annotations/lib/Doctrine/Common/Annotations',
        ),
        'Doctrine\\Common\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/common/lib/Doctrine/Common',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'ProxyManager\\' => 
            array (
                0 => __DIR__ . '/..' . '/ocramius/proxy-manager/src',
            ),
        ),
        'N' => 
        array (
            'Neos\\Neos\\Ui\\Compiled' => 
            array (
                0 => __DIR__ . '/../../..' . '/Packages/Application/Neos.Neos.Ui.Compiled/Classes',
            ),
        ),
        'I' => 
        array (
            'Imagine' => 
            array (
                0 => __DIR__ . '/..' . '/imagine/imagine/lib',
            ),
        ),
        'F' => 
        array (
            'Flowpack\\Neos\\FrontendLogin' => 
            array (
                0 => __DIR__ . '/../../..' . '/Packages/Plugins/Flowpack.Neos.FrontendLogin/Classes',
            ),
        ),
        'D' => 
        array (
            'Doctrine\\DBAL\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/dbal/lib',
            ),
            'Doctrine\\Common\\Lexer\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/lexer/lib',
            ),
            'Doctrine\\Common\\Collections\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/collections/lib',
            ),
        ),
        'B' => 
        array (
            'Behat\\Transliterator' => 
            array (
                0 => __DIR__ . '/..' . '/behat/transliterator/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf5d5e17d8bcc6e5757c5f3af607b4a7d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf5d5e17d8bcc6e5757c5f3af607b4a7d::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitf5d5e17d8bcc6e5757c5f3af607b4a7d::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
