<?php 

namespace Neos\Neos\Ui\Aspects;

/*                                                                        *
 * This script belongs to the Neos Flow package "Neos.Neos.Ui".          *
 *                                                                        *
 *                                                                        */

use Neos\Flow\Annotations as Flow;
use Neos\Flow\Aop\JoinPointInterface;
use Neos\Flow\Session\SessionInterface;
use Neos\Neos\Controller\Backend\SchemaController;

/**
 * adds a Cache-Control: max-age=3600 header to the /schema/node-types endpoint; speeds up loading the new UI
 * if having many node types.
 *
 * NOTE: we currently do this in an aspect, to also increase performance on older Neos versions (some people still
 * need time to upgrade to the latest Neos version...)
 *
 * @Flow\Scope("singleton")
 * @Flow\Aspect
 */
class NodeTypeSchemaCacheHeaderAspect_Original
{

    /**
     * @Flow\Inject
     * @var SessionInterface
     */
    protected $session;

    /**
     * @Flow\Before("method(Neos\Neos\Controller\Backend\SchemaController->nodeTypeSchemaAction())")
     * @param JoinPointInterface $joinPoint
     * @return mixed
     */
    public function setControllerContextFromContentElementWrappingImplementation(JoinPointInterface $joinPoint)
    {
        if ($this->session->isStarted() && !$this->session->getData('__neosLegacyUiEnabled__')) {
            /** @var SchemaController $proxy */
            $proxy = $joinPoint->getProxy();

            // Cache for one week!
            $proxy->getControllerContext()->getResponse()->setHeader('Cache-Control', 'max-age=' . (3600 * 24 * 7));
        }
    }
}

#
# Start of Flow generated Proxy code
#
namespace Neos\Neos\Ui\Aspects;

use Doctrine\ORM\Mapping as ORM;
use Neos\Flow\Annotations as Flow;

/**
 * adds a Cache-Control: max-age=3600 header to the /schema/node-types endpoint; speeds up loading the new UI
 * if having many node types.
 * 
 * NOTE: we currently do this in an aspect, to also increase performance on older Neos versions (some people still
 * need time to upgrade to the latest Neos version...)
 * @\Neos\Flow\Annotations\Scope("singleton")
 * @\Neos\Flow\Annotations\Aspect
 */
class NodeTypeSchemaCacheHeaderAspect extends NodeTypeSchemaCacheHeaderAspect_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if (get_class($this) === 'Neos\Neos\Ui\Aspects\NodeTypeSchemaCacheHeaderAspect') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Neos\Ui\Aspects\NodeTypeSchemaCacheHeaderAspect', $this);
        if ('Neos\Neos\Ui\Aspects\NodeTypeSchemaCacheHeaderAspect' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();

        $transientProperties = array (
);
        $propertyVarTags = array (
  'session' => 'Neos\\Flow\\Session\\SessionInterface',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {
        if (get_class($this) === 'Neos\Neos\Ui\Aspects\NodeTypeSchemaCacheHeaderAspect') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Neos\Ui\Aspects\NodeTypeSchemaCacheHeaderAspect', $this);

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->session = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Session\SessionInterface');
        $this->Flow_Injected_Properties = array (
  0 => 'session',
);
    }
}
# PathAndFilename: C:\Bitnami\neos-4.1.7-neu\apps\neos\htdocs\Packages\Application\Neos.Neos.Ui\Classes\Aspects\NodeTypeSchemaCacheHeaderAspect.php
#