<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const ROOT_PACKAGE_NAME = 'neos/neos-base-distribution';
    const VERSIONS = array (
  'behat/transliterator' => 'v1.2.0@826ce7e9c2a6664c0d1f381cbb38b1fb80a7ee2c',
  'doctrine/annotations' => 'v1.6.0@c7f2050c68a9ab0bdb0f98567ec08d80ea7d24d5',
  'doctrine/cache' => 'v1.8.0@d768d58baee9a4862ca783840eca1b9add7a7f57',
  'doctrine/collections' => 'v1.5.0@a01ee38fcd999f34d9bfbcee59dbda5105449cbf',
  'doctrine/common' => 'v2.7.3@4acb8f89626baafede6ee5475bc5844096eba8a9',
  'doctrine/dbal' => 'v2.7.2@c0e5736016a51b427a8cba8bc470fbea78165819',
  'doctrine/inflector' => 'v1.3.0@5527a48b7313d15261292c149e55e26eae771b0a',
  'doctrine/instantiator' => '1.1.0@185b8868aa9bf7159f5f953ed5afb2d7fcdc3bda',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'doctrine/migrations' => 'v1.6.2@e3faf7c96b8a6084045dedcaf51f74c7834644d4',
  'doctrine/orm' => 'v2.6.2@d2b4dd71d2a276edd65d0c170375b445f8a4a4a8',
  'flowpack/neos-frontendlogin' => '3.0.3@a52b456f31a8a6aaaf639913da648c29d68377e0',
  'gedmo/doctrine-extensions' => 'v2.4.36@87c78ff9fd4b90460386f753d95622f6fbbfcb27',
  'imagine/imagine' => 'v0.7.1@a9a702a946073cbca166718f1b02a1e72d742daa',
  'neos/cache' => '5.1.2@a693fe38610d92d29bfff85837190030a0e35707',
  'neos/composer-plugin' => '2.0.1@cd20e3c9b548127f4fa1e0f31662072bf82250d4',
  'neos/content-repository' => '4.1.7@21d10ae963ded991573f2d1f6e5c1ac5a94680a6',
  'neos/demo' => '4.1.7@49fcab93f4448a94e08c01c0ebeaea7d025030b2',
  'neos/diff' => '4.1.7@375302baf7a27f4bb0379997330b4860fb3f9c13',
  'neos/eel' => '5.1.2@8fe4f5d1ebf5f2e0e3e2851c0c2b7f956b3c98e7',
  'neos/error-messages' => '5.1.2@9c8ea6b492b57521ba0cd6f97938e2071a664ff6',
  'neos/flow' => '5.1.2@939f87de355fc865e3396d01a88ec44769df1f7e',
  'neos/flow-log' => '5.1.2@79e2a9ffd1c8c9c1b4816b38b26121a577427177',
  'neos/fluid-adaptor' => '5.1.2@b530698a93b29ab9ff898ce9a8390e6788f39555',
  'neos/form' => '4.1.4@6c16d54a58d92e61762d4cd193051bc001a00da1',
  'neos/fusion' => '4.1.7@f25aea1969f9708c946e9f73e7b33f51916cc4a1',
  'neos/imagine' => '3.0.5@b0a2feed9c830c0680937e2ffc897bc2da309f73',
  'neos/kickstarter' => '5.1.2@44d36f2b2034e750e728e30c86acfd075f7bda36',
  'neos/media' => '4.1.7@4a4e1897313674d18f8fdc1291a6f5c6e0d4348d',
  'neos/media-browser' => '4.1.7@da8a217b73568c11d1315b498df62e9845fa02b1',
  'neos/neos' => '4.1.7@e4d9277e98b3994ff6e029411472ee5085d7ad65',
  'neos/neos-ui' => '1.3.4@713387c79dbe591d039d0ab0c5789ae1cf9bf854',
  'neos/neos-ui-compiled' => '1.3.4@386cb52759c0498a7eeade1680c40df021b101df',
  'neos/nodetypes' => '4.1.7@a1d57e23d61132c45ba7dbadb06caade2c904019',
  'neos/nodetypes-assetlist' => '4.1.7@63095f33be7fa10c497fd2cf9fbbd89a86d33a5b',
  'neos/nodetypes-basemixins' => '4.1.7@0b97f38688e701b678e395b6a48533b9064cbbf0',
  'neos/nodetypes-columnlayouts' => '4.1.7@2d0c05d006ae1089b7ffdf659c2f92dc6a56256c',
  'neos/nodetypes-contentreferences' => '4.1.7@42c31c310f2d97b245cc8d7c5fe7f10581dcf2a5',
  'neos/nodetypes-form' => '4.1.7@03425ff82ebc9602e9f9b041ce447d250fc29156',
  'neos/nodetypes-html' => '4.1.7@8902570fe4946c7f32c01c5f1f5bf056efd3c7c8',
  'neos/nodetypes-navigation' => '4.1.7@491ed87bb59b83cdc03c4fdcdce49e48fa6d7ef9',
  'neos/party' => '5.0.1@c6d7b17c9aedcb3fe5dcd8ee0a0980d83986516c',
  'neos/redirecthandler' => '2.0.1@351effbe2d184e82cc1dc65a5e409d092ba56194',
  'neos/redirecthandler-databasestorage' => '2.0.1@463efeb2f8c825b0c62500e365aec423ea152560',
  'neos/redirecthandler-neosadapter' => '2.0.4@9b675edbffe0e50f9c6e38f88f3d03a8b263ad7c',
  'neos/seo' => '2.0.10@43186bf8f8cf0c6f8548509382c932dc7aa5e780',
  'neos/setup' => '4.0.6@9af0a191e135c998a4b0e9e40de8cef537271e36',
  'neos/site-kickstarter' => '4.1.7@c3c3c38a768cfeddd9e9ae2d5d3bc55a13c717a9',
  'neos/twitter-bootstrap' => '3.0.4@f1da794467a79d9a9be113749a2c9d38cf8c1eec',
  'neos/utility-arrays' => '5.1.2@13e13742cb9b2073f37a825e109615824bc7ecd6',
  'neos/utility-files' => '5.1.2@a9a10334da7c438f28634540747ff70bf405cff2',
  'neos/utility-lock' => '5.1.2@b9a59db6cf3d1876aeed88fca7df44d7ccf5c8f1',
  'neos/utility-mediatypes' => '5.1.2@b954f3cafad4eb6bde3a99ccf8632447673c3307',
  'neos/utility-objecthandling' => '5.1.2@604bbfda049b1b3bc752bcc6a8363f2ac3734fc7',
  'neos/utility-opcodecache' => '5.1.2@e3a7536809c90dedb93bd8e6e98184728aeb9daa',
  'neos/utility-pdo' => '5.1.2@3091215c460563347f53ac5fb39349ab663acc0f',
  'neos/utility-schema' => '5.1.2@212f4830ab6977fe628106a49b772651c52f53b3',
  'neos/utility-unicode' => '5.1.2@06c406587c384bb938ecfa299c69953793e9a23b',
  'ocramius/package-versions' => '1.3.0@4489d5002c49d55576fa0ba786f42dbb009be46f',
  'ocramius/proxy-manager' => '2.1.1@e18ac876b2e4819c76349de8f78ccc8ef1554cd7',
  'paragonie/random_compat' => 'v9.99.99@84b4dfb120c6f9b4ff7b3685f9b8f1aa365a0c95',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/container' => '1.0.0@b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/log' => '1.0.2@4ebe3a8bf773a19edfe0a84b6585ba3d401b724d',
  'psr/simple-cache' => '1.0.1@408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
  'ramsey/uuid' => '3.8.0@d09ea80159c1929d75b3f9c60504d613aeb4a1e3',
  'symfony/console' => 'v4.0.14@3179d1350843d2caa796973173dd0609ed4c7c67',
  'symfony/dom-crawler' => 'v4.0.14@d370b259c534414fff0be798618235b7f563b26f',
  'symfony/polyfill-ctype' => 'v1.9.0@e3d826245268269cd66f8326bd8bc066687b4a19',
  'symfony/polyfill-mbstring' => 'v1.9.0@d0cd638f4634c16d8df4508e847f14e9e43168b8',
  'symfony/yaml' => 'v4.0.14@05f66d707cfa60d553e419ec038d5474c2d5d1f2',
  'typo3fluid/fluid' => '2.5.4@bcd0ff44dd3c4f9d0f37097b0237db6319c2b181',
  'zendframework/zend-code' => '3.3.1@c21db169075c6ec4b342149f446e7b7b724f95eb',
  'zendframework/zend-eventmanager' => '3.2.1@a5e2583a211f73604691586b8406ff7296a946dd',
  'mikey179/vfsStream' => 'v1.6.5@d5fec95f541d4d71c4823bb5e30cf9b9e5b96145',
  'myclabs/deep-copy' => '1.8.1@3e01bdad3e18354c3dce54466b7fbe33a9f9f7f8',
  'neos/behat' => 'dev-master@0b7c4f6bb1dbfe4e7115770c0d7ca2a58be896bd',
  'neos/buildessentials' => '5.1.0@b54950e194fad1badcb02d4708012780e786ec31',
  'phar-io/manifest' => '1.0.3@7761fcacf03b4d4f16e7ccb606d4879ca431fcf4',
  'phar-io/version' => '2.0.1@45a2ec53a73c70ce41d55cedef9063630abaf1b6',
  'phpdocumentor/reflection-common' => '1.0.1@21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
  'phpdocumentor/reflection-docblock' => '4.3.0@94fd0001232e47129dd3504189fa1c7225010d08',
  'phpdocumentor/type-resolver' => '0.4.0@9c977708995954784726e25d0cd1dddf4e65b0f7',
  'phpspec/prophecy' => '1.8.0@4ba436b55987b4bf311cb7c6ba82aa528aac0a06',
  'phpunit/php-code-coverage' => '6.0.7@865662550c384bc1db7e51d29aeda1c2c161d69a',
  'phpunit/php-file-iterator' => '2.0.2@050bedf145a257b1ff02746c31894800e5122946',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '2.0.0@8b8454ea6958c3dee38453d3bd571e023108c91f',
  'phpunit/php-token-stream' => '3.0.0@21ad88bbba7c3d93530d93994e0a33cd45f02ace',
  'phpunit/phpunit' => '7.3.5@7b331efabbb628c518c408fdfcaf571156775de2',
  'sebastian/code-unit-reverse-lookup' => '1.0.1@4419fcdb5eabb9caa61a27c7a1db532a6b55dd18',
  'sebastian/comparator' => '3.0.2@5de4fc177adf9bce8df98d8d141a7559d7ccf6da',
  'sebastian/diff' => '3.0.1@366541b989927187c4ca70490a35615d3fef2dce',
  'sebastian/environment' => '3.1.0@cd0871b3975fb7fc44d11314fd1ee20925fce4f5',
  'sebastian/exporter' => '3.1.0@234199f4528de6d12aaa58b612e98f7d36adb937',
  'sebastian/global-state' => '2.0.0@e8ba02eed7bbbb9e59e43dedd3dddeff4a56b0c4',
  'sebastian/object-enumerator' => '3.0.3@7cfd9e65d11ffb5af41198476395774d4c8a84c5',
  'sebastian/object-reflector' => '1.1.1@773f97c67f28de00d397be301821b06708fca0be',
  'sebastian/recursion-context' => '3.0.0@5b0cd723502bac3b006cbf3dbf7a1e3fcefe4fa8',
  'sebastian/resource-operations' => '1.0.0@ce990bb21759f94aeafd30209e8cfcdfa8bc3f52',
  'sebastian/version' => '2.0.1@99732be0ddb3361e16ad77b68ba41efc8e979019',
  'symfony/css-selector' => 'v2.8.46@4cca41ebe83cd5b4bd0c1a9f6bdfaec7103f97fb',
  'theseer/tokenizer' => '1.1.0@cb2f008f3f05af2893a87208fe6a6c4985483f8b',
  'webmozart/assert' => '1.3.0@0df1908962e7a3071564e857d86874dad1ef204a',
  'typo3/neos-base-distribution' => '4.1.7@',
  'neos/neos-base-distribution' => '4.1.7@',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion(string $packageName) : string
    {
        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new \OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: cannot detect its version'
        );
    }
}
